name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Start API server
      run: |
        uvicorn api:app --host 127.0.0.1 --port 8080 &
        echo "API_PID=$!" >> $GITHUB_ENV
      env:
        TOKEN: ${{ secrets.TOKEN }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    - name: Print TOKEN variable
      run: |
        echo "TOKEN: $TOKEN"
      env:
        TOKEN: ${{ secrets.TOKEN }}

    - name: Run tests
      run: |
        TOKEN: $TOKEN
        pytest
      env:
        TOKEN: ${{ secrets.TOKEN }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    - name: Stop API server
      run: |
        kill $API_PID
