name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python run_tests.py

      - name: Deploy to Heroku
        if: success() # Only deploy if all previous steps were successful (tests passed)
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "apiepsicrm" # Replace with your Heroku app name
          heroku_email: "hugo.fugeray@gmail.com" # Replace with your Heroku account email
          branch: main
