name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Start API server
      run: |
        uvicorn api:app --host 127.0.0.1 --port 8080 &
        echo "API_PID=$!" >> $GITHUB_ENV
      env:
        TOK: ${{ secrets.TOK }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    - name: Run tests
      run: |

        pytest
      env:
        TOK: ${{ secrets.TOK }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    - name: Stop API server
      run: |
        kill $API_PID

    - name: Set up Heroku CLI
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - name: Login to Heroku
      run: |
        heroku login -i
        heroku container:login
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
    - name: Build and push Docker container to Heroku
      run: |
        heroku container:push -a apiepsicrm web
        heroku container:release -a apiepsicrm web
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

